### ISSUE TITLE
Lista Utenti non trovata

### ISSUE THREAD

**Issue by Raquaza98** [Lorenzo-Orlando-JCMaxwell-5AI/Java-Sockets#1]
Il comando per visualizzare la lista utenti non visualizza niente, si prega di aggiustare il codice

**Comment by Lorenzo-Orlando-JCMaxwell-5AI** [comment]
Il problema non è che non visualizza niente, ma che il comando visualizza solo solo il client che effettua il comando.

**Comment by Raquaza98** [comment]
Se possibile, modifichi il codice in modo da ottenere la lista completa degli utenti sotto richiesta del client

**Comment by Lorenzo-Orlando-JCMaxwell-5AI** [comment]
Riesci a darmi una mano grazie. XD

**Comment by Raquaza98** [comment]
Posso darti una mano se necessario

**Comment by Lorenzo-Orlando-JCMaxwell-5AI** [comment]
Ho usato una lista nel soketWorker ma penso andrebbe usata nel server solo che non so come fare
